[package]
name = "vegas-rs"
version = "0.1.0"
authors = ["Oscar David ArbelÃ¡ez Echeverri <odarbelaeze@gmail.com>"]

[lib]
name = "vegas"
path = "src/vegas/lib.rs"

[[bin]]
name = "vegas"
path = "src/bin/main.rs"

[dependencies]
rand = "0.3"
