model = "Ising"
algorithm = "Wolff"

[sample.unitcell]
name = "sc"

[sample.size]
x = 10
y = 10
z = 10

[sample.pbc]
x = true
y = true
z = true

[[steps]]
program = "Relax"
steps = 1000
temperature = 6.0

[[steps]]
program = "CoolDown"
max_temperature = 6.0
min_temperature = 1.0
cool_rate = 0.05
relax = 1000
steps = 20000

[output]
observables = "./output.parquet"

[output.state]
path = "./state.parquet"
frequency = 1000
